// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pwa.proxies;

public class Icons
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject iconsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PWA.Icons";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Icons_Root("PWA.Icons_Root"),
		Icons_Icon("PWA.Icons_Icon");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Icons(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PWA.Icons"));
	}

	protected Icons(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject iconsMendixObject)
	{
		if (iconsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PWA.Icons", iconsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PWA.Icons");

		this.iconsMendixObject = iconsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Icons.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pwa.proxies.Icons initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pwa.proxies.Icons.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pwa.proxies.Icons initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pwa.proxies.Icons(context, mendixObject);
	}

	public static pwa.proxies.Icons load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pwa.proxies.Icons.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Icons_Root
	 */
	public final pwa.proxies.Root getIcons_Root() throws com.mendix.core.CoreException
	{
		return getIcons_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Icons_Root
	 */
	public final pwa.proxies.Root getIcons_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pwa.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Icons_Root.toString());
		if (identifier != null)
			result = pwa.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Icons_Root
	 * @param icons_root
	 */
	public final void setIcons_Root(pwa.proxies.Root icons_root)
	{
		setIcons_Root(getContext(), icons_root);
	}

	/**
	 * Set value of Icons_Root
	 * @param context
	 * @param icons_root
	 */
	public final void setIcons_Root(com.mendix.systemwideinterfaces.core.IContext context, pwa.proxies.Root icons_root)
	{
		if (icons_root == null)
			getMendixObject().setValue(context, MemberNames.Icons_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Icons_Root.toString(), icons_root.getMendixObject().getId());
	}

	/**
	 * @return value of Icons_Icon
	 */
	public final java.util.List<pwa.proxies.Icon> getIcons_Icon() throws com.mendix.core.CoreException
	{
		return getIcons_Icon(getContext());
	}

	/**
	 * @param context
	 * @return value of Icons_Icon
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<pwa.proxies.Icon> getIcons_Icon(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<pwa.proxies.Icon> result = new java.util.ArrayList<pwa.proxies.Icon>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Icons_Icon.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(pwa.proxies.Icon.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Icons_Icon
	 * @param icons_icon
	 */
	public final void setIcons_Icon(java.util.List<pwa.proxies.Icon> icons_icon)
	{
		setIcons_Icon(getContext(), icons_icon);
	}

	/**
	 * Set value of Icons_Icon
	 * @param context
	 * @param icons_icon
	 */
	public final void setIcons_Icon(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<pwa.proxies.Icon> icons_icon)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (pwa.proxies.Icon proxyObject : icons_icon)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Icons_Icon.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return iconsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pwa.proxies.Icons that = (pwa.proxies.Icons) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PWA.Icons";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
