// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pwa.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PWA.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Short_name("Short_name"),
		Name("Name"),
		Start_url("Start_url"),
		Background_color("Background_color"),
		Display("Display"),
		Scope("Scope"),
		Theme_color("Theme_color"),
		Icons_Root("PWA.Icons_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PWA.Root"));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PWA.Root", rootMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PWA.Root");

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pwa.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pwa.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pwa.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pwa.proxies.Root(context, mendixObject);
	}

	public static pwa.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pwa.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Short_name
	 */
	public final java.lang.String getShort_name()
	{
		return getShort_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Short_name
	 */
	public final java.lang.String getShort_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Short_name.toString());
	}

	/**
	 * Set value of Short_name
	 * @param short_name
	 */
	public final void setShort_name(java.lang.String short_name)
	{
		setShort_name(getContext(), short_name);
	}

	/**
	 * Set value of Short_name
	 * @param context
	 * @param short_name
	 */
	public final void setShort_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String short_name)
	{
		getMendixObject().setValue(context, MemberNames.Short_name.toString(), short_name);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Start_url
	 */
	public final java.lang.String getStart_url()
	{
		return getStart_url(getContext());
	}

	/**
	 * @param context
	 * @return value of Start_url
	 */
	public final java.lang.String getStart_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Start_url.toString());
	}

	/**
	 * Set value of Start_url
	 * @param start_url
	 */
	public final void setStart_url(java.lang.String start_url)
	{
		setStart_url(getContext(), start_url);
	}

	/**
	 * Set value of Start_url
	 * @param context
	 * @param start_url
	 */
	public final void setStart_url(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String start_url)
	{
		getMendixObject().setValue(context, MemberNames.Start_url.toString(), start_url);
	}

	/**
	 * @return value of Background_color
	 */
	public final java.lang.String getBackground_color()
	{
		return getBackground_color(getContext());
	}

	/**
	 * @param context
	 * @return value of Background_color
	 */
	public final java.lang.String getBackground_color(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Background_color.toString());
	}

	/**
	 * Set value of Background_color
	 * @param background_color
	 */
	public final void setBackground_color(java.lang.String background_color)
	{
		setBackground_color(getContext(), background_color);
	}

	/**
	 * Set value of Background_color
	 * @param context
	 * @param background_color
	 */
	public final void setBackground_color(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String background_color)
	{
		getMendixObject().setValue(context, MemberNames.Background_color.toString(), background_color);
	}

	/**
	 * @return value of Display
	 */
	public final java.lang.String getDisplay()
	{
		return getDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of Display
	 */
	public final java.lang.String getDisplay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Display.toString());
	}

	/**
	 * Set value of Display
	 * @param display
	 */
	public final void setDisplay(java.lang.String display)
	{
		setDisplay(getContext(), display);
	}

	/**
	 * Set value of Display
	 * @param context
	 * @param display
	 */
	public final void setDisplay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String display)
	{
		getMendixObject().setValue(context, MemberNames.Display.toString(), display);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return value of Theme_color
	 */
	public final java.lang.String getTheme_color()
	{
		return getTheme_color(getContext());
	}

	/**
	 * @param context
	 * @return value of Theme_color
	 */
	public final java.lang.String getTheme_color(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Theme_color.toString());
	}

	/**
	 * Set value of Theme_color
	 * @param theme_color
	 */
	public final void setTheme_color(java.lang.String theme_color)
	{
		setTheme_color(getContext(), theme_color);
	}

	/**
	 * Set value of Theme_color
	 * @param context
	 * @param theme_color
	 */
	public final void setTheme_color(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String theme_color)
	{
		getMendixObject().setValue(context, MemberNames.Theme_color.toString(), theme_color);
	}

	/**
	 * @return value of Icons_Root
	 */
	public final pwa.proxies.Icons getIcons_Root() throws com.mendix.core.CoreException
	{
		return getIcons_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Icons_Root
	 */
	public final pwa.proxies.Icons getIcons_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pwa.proxies.Icons result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Icons_Root.toString());
		if (identifier != null)
			result = pwa.proxies.Icons.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Icons_Root
	 * @param icons_root
	 */
	public final void setIcons_Root(pwa.proxies.Icons icons_root)
	{
		setIcons_Root(getContext(), icons_root);
	}

	/**
	 * Set value of Icons_Root
	 * @param context
	 * @param icons_root
	 */
	public final void setIcons_Root(com.mendix.systemwideinterfaces.core.IContext context, pwa.proxies.Icons icons_root)
	{
		if (icons_root == null)
			getMendixObject().setValue(context, MemberNames.Icons_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Icons_Root.toString(), icons_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pwa.proxies.Root that = (pwa.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PWA.Root";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
